[project]
name = "ex-basics-1-pluto"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[tool.uv]
publish-url = "https://test.pypi.org/legacy/"

