[project]
name = "ex-basics-1-pluto"
version = "0.3.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "typer>=0.16.1",
]

[tool.uv]
publish-url = "https://test.pypi.org/legacy/"